theme: jekyll-theme-cayman
title: Corneliu's Pages
description: DevOps, Microservices and related
google_analytics: UA-30085866-2
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
exclude:
  - kb/_template.md
